// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using DbDesigner.Infrastructure;

#nullable disable

namespace DbDesigner.Infrastructure.Migrations
{
    [DbContext(typeof(DbDesignerContext))]
    [Migration("20250213123413_update sql types")]
    partial class updatesqltypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DbDesigner.Domain.Domain.Architecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Architectures");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Column", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SqlTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("SqlTypeParams")
                        .HasColumnType("text");

                    b.Property<int>("TableId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SqlTypeId");

                    b.HasIndex("TableId");

                    b.ToTable("Columns");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.ColumnProperty", b =>
                {
                    b.Property<int>("ColumnId")
                        .HasColumnType("integer");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<string>("PropertyParams")
                        .HasColumnType("text");

                    b.HasKey("ColumnId", "PropertyId");

                    b.HasIndex("PropertyId");

                    b.ToTable("ColumnProperties");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.DataBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataBases");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Index", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("IndexTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IndexTypeId");

                    b.ToTable("Indices");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.IndexColumn", b =>
                {
                    b.Property<int>("ColumnId")
                        .HasColumnType("integer");

                    b.Property<int>("IndexId")
                        .HasColumnType("integer");

                    b.HasKey("ColumnId", "IndexId");

                    b.HasIndex("IndexId");

                    b.ToTable("IndexColumns");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.IndexType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DataBaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataBaseId");

                    b.ToTable("IndexTypes");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.LanguageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("LanguageTypes");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.LanguageTypeSqlType", b =>
                {
                    b.Property<int>("LanguageTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("SqlTypeId")
                        .HasColumnType("integer");

                    b.HasKey("LanguageTypeId", "SqlTypeId");

                    b.HasIndex("SqlTypeId");

                    b.ToTable("LanguageTypeSqlTypes");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Orm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Orms");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DataBaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataBaseId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("HasParams")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Relation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OnDeleteId")
                        .HasColumnType("integer");

                    b.Property<int>("OnUpdateId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceColumnId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetColumnId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OnDeleteId");

                    b.HasIndex("OnUpdateId");

                    b.HasIndex("SourceColumnId");

                    b.HasIndex("TargetColumnId");

                    b.ToTable("Relations");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.RelationAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RelationActions");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.SqlType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DataBaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("HasParams")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataBaseId");

                    b.ToTable("SqlTypes");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.UserProject", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserProjects");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Column", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.SqlType", "SqlType")
                        .WithMany("Columns")
                        .HasForeignKey("SqlTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbDesigner.Domain.Domain.Table", "Table")
                        .WithMany("Columns")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SqlType");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.ColumnProperty", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.Column", null)
                        .WithMany()
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbDesigner.Domain.Domain.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Index", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.IndexType", "IndexType")
                        .WithMany()
                        .HasForeignKey("IndexTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndexType");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.IndexColumn", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.Column", null)
                        .WithMany()
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbDesigner.Domain.Domain.Index", null)
                        .WithMany()
                        .HasForeignKey("IndexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.IndexType", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.DataBase", "DataBase")
                        .WithMany("IndexTypes")
                        .HasForeignKey("DataBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataBase");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.LanguageType", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.LanguageTypeSqlType", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.LanguageType", null)
                        .WithMany()
                        .HasForeignKey("LanguageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbDesigner.Domain.Domain.SqlType", null)
                        .WithMany()
                        .HasForeignKey("SqlTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Orm", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.Language", "Language")
                        .WithMany("Orms")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Project", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.DataBase", "DataBase")
                        .WithMany("Projects")
                        .HasForeignKey("DataBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataBase");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Relation", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.RelationAction", "OnDelete")
                        .WithMany()
                        .HasForeignKey("OnDeleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbDesigner.Domain.Domain.RelationAction", "OnUpdate")
                        .WithMany()
                        .HasForeignKey("OnUpdateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbDesigner.Domain.Domain.Column", "SourceColumn")
                        .WithMany()
                        .HasForeignKey("SourceColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbDesigner.Domain.Domain.Column", "TargetColumn")
                        .WithMany()
                        .HasForeignKey("TargetColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OnDelete");

                    b.Navigation("OnUpdate");

                    b.Navigation("SourceColumn");

                    b.Navigation("TargetColumn");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.SqlType", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.DataBase", "DataBase")
                        .WithMany("SqlTypes")
                        .HasForeignKey("DataBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataBase");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Table", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.Project", "Project")
                        .WithMany("Tables")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.UserProject", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbDesigner.Domain.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.UserRole", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbDesigner.Domain.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.DataBase", b =>
                {
                    b.Navigation("IndexTypes");

                    b.Navigation("Projects");

                    b.Navigation("SqlTypes");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Language", b =>
                {
                    b.Navigation("Orms");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Project", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.SqlType", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Table", b =>
                {
                    b.Navigation("Columns");
                });
#pragma warning restore 612, 618
        }
    }
}
