// <auto-generated />
using System;
using DbDesigner.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DbDesigner.Infrastructure.Migrations
{
    [DbContext(typeof(DbDesignerContext))]
    [Migration("20250301190505_delete user project")]
    partial class deleteuserproject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DbDesigner.Domain.Domain.Architecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Architectures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "An approach in which code interacts directly with the database, without the use of abstraction layers.",
                            Name = "Direct Data Access (DDA)"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A design pattern that provides an abstraction for working with data, allowing data access logic to be separated from business logic.",
                            Name = "Repository"
                        },
                        new
                        {
                            Id = 3,
                            Description = "An architectural pattern that separates state change operations (commands) from data requests (reads), ensuring their independence.",
                            Name = "Command Query Responsibility Segregation (CQRS)"
                        });
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Column", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SqlTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("SqlTypeParams")
                        .HasColumnType("text");

                    b.Property<int>("TableId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SqlTypeId");

                    b.HasIndex("TableId");

                    b.ToTable("Columns");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.ColumnProperty", b =>
                {
                    b.Property<int>("ColumnId")
                        .HasColumnType("integer");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<string>("PropertyParams")
                        .HasColumnType("text");

                    b.HasKey("ColumnId", "PropertyId");

                    b.HasIndex("PropertyId");

                    b.ToTable("ColumnProperties");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.DataBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataBases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "An open object-relational DBMS with support for complex queries, extensions and highly reliable transactions.",
                            Image = "PostgreSQL.png",
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A popular and fast open DBMS, widely used in web applications due to its ease of configuration and cross-platform functionality.",
                            Image = "MySQL.png",
                            Name = "MySQL"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A lightweight embedded DBMS that does not require a server, ideal for mobile applications and prototyping.",
                            Image = "SQLite.png",
                            Name = "SQLite"
                        });
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Index", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("IndexTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IndexTypeId");

                    b.ToTable("Indices");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.IndexColumn", b =>
                {
                    b.Property<int>("ColumnId")
                        .HasColumnType("integer");

                    b.Property<int>("IndexId")
                        .HasColumnType("integer");

                    b.HasKey("ColumnId", "IndexId");

                    b.HasIndex("IndexId");

                    b.ToTable("IndexColumns");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.IndexType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DataBaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataBaseId");

                    b.ToTable("IndexTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataBaseId = 3,
                            Description = "Standard index that improves query performance by allowing faster data retrieval. Data is logically ordered, but not physically stored in the index order.",
                            Name = "Index"
                        },
                        new
                        {
                            Id = 2,
                            DataBaseId = 3,
                            Description = "Ensures that all values in the indexed column(s) are unique. Improves query performance and enforces data integrity by preventing duplicate entries.",
                            Name = "Unique Index"
                        },
                        new
                        {
                            Id = 3,
                            DataBaseId = 2,
                            Description = "Default index type in MySQL. Suitable for most queries, including equality checks, range queries, and sorting. Data is stored in a balanced tree structure.",
                            Name = "B-tree"
                        },
                        new
                        {
                            Id = 4,
                            DataBaseId = 2,
                            Description = "Ensures that all values in the indexed column(s) are unique. Improves query performance and enforces data integrity by preventing duplicate entries.",
                            Name = "Unique Index"
                        },
                        new
                        {
                            Id = 5,
                            DataBaseId = 2,
                            Description = "Optimized for full-text search queries. Allows efficient searching of text data using natural language queries.",
                            Name = "Full-text Index"
                        },
                        new
                        {
                            Id = 6,
                            DataBaseId = 1,
                            Description = "Default index type in PostgreSQL. Suitable for most queries, including equality checks, range queries, and sorting. Data is stored in a balanced tree structure.",
                            Name = "B-tree"
                        },
                        new
                        {
                            Id = 7,
                            DataBaseId = 1,
                            Description = "Optimized for equality checks (=). Provides fast lookups but does not support range queries or sorting. Suitable for exact match queries.",
                            Name = "Hash"
                        },
                        new
                        {
                            Id = 8,
                            DataBaseId = 1,
                            Description = "Ensures that all values in the indexed column(s) are unique. Improves query performance and enforces data integrity by preventing duplicate entries.",
                            Name = "Unique Index"
                        });
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "An object-oriented programming language from Microsoft, widely used for developing enterprise applications, games and web services.",
                            Image = "cs.png",
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A high-level programming language with a simple syntactic structure, popular for development, automation, data analysis and machine learning.",
                            Image = "py.png",
                            Name = "Python"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A scripting language for developing interactive web pages, also actively used in server and mobile applications.",
                            Image = "js.png",
                            Name = "JavaScript"
                        });
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Orm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Orms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "An ORM for C# and .NET that provides a high level of abstraction for working with databases, allowing you to use LINQ for queries.",
                            LanguageId = 1,
                            Name = "Entity Framework"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A popular ORM for Python that supports powerful mapping and database schema management.",
                            LanguageId = 2,
                            Name = "SQLAlchemy"
                        },
                        new
                        {
                            Id = 3,
                            Description = "ORM for Node.js with support for various relational databases and a powerful interface for working with SQL queries.",
                            LanguageId = 3,
                            Name = "Sequelize"
                        });
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DataBaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataBaseId");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DataBaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("HasParams")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataBaseId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataBaseId = 3,
                            Description = "Uniquely identifies each row in the table. Automatically enforces uniqueness and creates an index.",
                            HasParams = false,
                            Name = "PRIMARY KEY"
                        },
                        new
                        {
                            Id = 2,
                            DataBaseId = 3,
                            Description = "Ensures that all values in the column are unique. Prevents duplicate entries.",
                            HasParams = false,
                            Name = "UNIQUE"
                        },
                        new
                        {
                            Id = 3,
                            DataBaseId = 3,
                            Description = "Ensures that the column cannot contain NULL values.",
                            HasParams = false,
                            Name = "NOT NULL"
                        },
                        new
                        {
                            Id = 4,
                            DataBaseId = 3,
                            Description = "Sets a default value for the column if no value is provided during insertion.",
                            HasParams = true,
                            Name = "DEFAULT"
                        },
                        new
                        {
                            Id = 5,
                            DataBaseId = 3,
                            Description = "Enforces a condition that must be true for all values in the column.",
                            HasParams = true,
                            Name = "CHECK"
                        },
                        new
                        {
                            Id = 6,
                            DataBaseId = 2,
                            Description = "Uniquely identifies each row in the table. Automatically enforces uniqueness and creates an index.",
                            HasParams = false,
                            Name = "PRIMARY KEY"
                        },
                        new
                        {
                            Id = 7,
                            DataBaseId = 2,
                            Description = "Automatically generates a unique value for the column, incrementing with each new row.",
                            HasParams = false,
                            Name = "AUTO INCREMENT"
                        },
                        new
                        {
                            Id = 8,
                            DataBaseId = 2,
                            Description = "Ensures that all values in the column are unique. Prevents duplicate entries.",
                            HasParams = false,
                            Name = "UNIQUE"
                        },
                        new
                        {
                            Id = 9,
                            DataBaseId = 2,
                            Description = "Ensures that the column cannot contain NULL values.",
                            HasParams = false,
                            Name = "NOT NULL"
                        },
                        new
                        {
                            Id = 10,
                            DataBaseId = 2,
                            Description = "Sets a default value for the column if no value is provided during insertion.",
                            HasParams = true,
                            Name = "DEFAULT"
                        },
                        new
                        {
                            Id = 11,
                            DataBaseId = 2,
                            Description = "Enforces a condition that must be true for all values in the column.",
                            HasParams = true,
                            Name = "CHECK"
                        },
                        new
                        {
                            Id = 12,
                            DataBaseId = 2,
                            Description = "Restricts the column to non-negative numeric values.",
                            HasParams = false,
                            Name = "UNSIGNED"
                        },
                        new
                        {
                            Id = 13,
                            DataBaseId = 1,
                            Description = "Uniquely identifies each row in the table. Automatically enforces uniqueness and creates an index.",
                            HasParams = false,
                            Name = "PRIMARY KEY"
                        },
                        new
                        {
                            Id = 14,
                            DataBaseId = 1,
                            Description = "Automatically generates a unique value for the column, similar to auto-increment but compliant with SQL standards.",
                            HasParams = false,
                            Name = "GENERATED AS IDENTITY"
                        },
                        new
                        {
                            Id = 15,
                            DataBaseId = 1,
                            Description = "Ensures that all values in the column are unique. Prevents duplicate entries.",
                            HasParams = false,
                            Name = "UNIQUE"
                        },
                        new
                        {
                            Id = 16,
                            DataBaseId = 1,
                            Description = "Ensures that the column cannot contain NULL values.",
                            HasParams = false,
                            Name = "NOT NULL"
                        },
                        new
                        {
                            Id = 17,
                            DataBaseId = 1,
                            Description = "Sets a default value for the column if no value is provided during insertion.",
                            HasParams = true,
                            Name = "DEFAULT"
                        },
                        new
                        {
                            Id = 18,
                            DataBaseId = 1,
                            Description = "Enforces a condition that must be true for all values in the column.",
                            HasParams = true,
                            Name = "CHECK"
                        });
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Relation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OnDeleteId")
                        .HasColumnType("integer");

                    b.Property<int>("OnUpdateId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceColumnId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetColumnId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OnDeleteId");

                    b.HasIndex("OnUpdateId");

                    b.HasIndex("SourceColumnId");

                    b.HasIndex("TargetColumnId");

                    b.ToTable("Relations");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.RelationAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RelationActions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "When you delete or update a parent record, the associated child records are automatically deleted or updated.",
                            Name = "CASCADE"
                        },
                        new
                        {
                            Id = 2,
                            Description = "When a parent record is deleted or updated, the corresponding foreign keys in the child records are set to NULL.",
                            Name = "SET NULL"
                        },
                        new
                        {
                            Id = 3,
                            Description = "When a parent record is deleted or updated, the foreign keys in the child records are set to the default value.",
                            Name = "SET DEFAULT"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Prevents a parent record from being deleted or updated if there are associated child records.",
                            Name = "RESTRICT"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Similar to RESTRICT, but data integrity checks are performed later, after all transaction actions.",
                            Name = "NO ACTION"
                        });
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.SqlType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DataBaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("HasParams")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataBaseId");

                    b.ToTable("SqlTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataBaseId = 3,
                            Description = "Stores integer values. Flexible storage (1, 2, 3, 4, 6, or 8 bytes depending on magnitude).",
                            HasParams = false,
                            Name = "INTEGER"
                        },
                        new
                        {
                            Id = 2,
                            DataBaseId = 3,
                            Description = "Stores floating-point numbers (8-byte IEEE double precision).",
                            HasParams = false,
                            Name = "REAL"
                        },
                        new
                        {
                            Id = 3,
                            DataBaseId = 3,
                            Description = "Stores UTF-8/UTF-16 encoded string values.",
                            HasParams = false,
                            Name = "TEXT"
                        },
                        new
                        {
                            Id = 4,
                            DataBaseId = 3,
                            Description = "Stores numeric values (integer or floating-point). Behaves like INTEGER/REAL based on context.",
                            HasParams = false,
                            Name = "NUMERIC"
                        },
                        new
                        {
                            Id = 5,
                            DataBaseId = 2,
                            Description = "4-byte signed integer. Range: -2,147,483,648 to 2,147,483,647.",
                            HasParams = false,
                            Name = "INT"
                        },
                        new
                        {
                            Id = 6,
                            DataBaseId = 2,
                            Description = "1-byte signed integer. Range: -128 to 127. UNSIGNED: 0 to 255.",
                            HasParams = false,
                            Name = "TINYINT"
                        },
                        new
                        {
                            Id = 7,
                            DataBaseId = 2,
                            Description = "2-byte signed integer. Range: -32,768 to 32,767. UNSIGNED: 0 to 65,535.",
                            HasParams = false,
                            Name = "SMALLINT"
                        },
                        new
                        {
                            Id = 8,
                            DataBaseId = 2,
                            Description = "3-byte signed integer. Range: -8,388,608 to 8,388,607. UNSIGNED: 0 to 16,777,215.",
                            HasParams = false,
                            Name = "MEDIUMINT"
                        },
                        new
                        {
                            Id = 9,
                            DataBaseId = 2,
                            Description = "8-byte signed integer. Range: -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807.",
                            HasParams = false,
                            Name = "BIGINT"
                        },
                        new
                        {
                            Id = 10,
                            DataBaseId = 2,
                            Description = "4-byte floating-point number (single precision). Approximate precision: 7 decimal digits.",
                            HasParams = false,
                            Name = "FLOAT"
                        },
                        new
                        {
                            Id = 11,
                            DataBaseId = 2,
                            Description = "8-byte floating-point number (double precision). Approximate precision: 15 decimal digits.",
                            HasParams = false,
                            Name = "DOUBLE"
                        },
                        new
                        {
                            Id = 12,
                            DataBaseId = 2,
                            Description = "Fixed-point number with exact precision. Syntax: DECIMAL(M,D) where M=total digits, D=decimal digits.",
                            HasParams = true,
                            Name = "DECIMAL"
                        },
                        new
                        {
                            Id = 13,
                            DataBaseId = 2,
                            Description = "Fixed-length string. Padded with spaces to specified length. Max length: 255 characters.",
                            HasParams = true,
                            Name = "CHAR"
                        },
                        new
                        {
                            Id = 14,
                            DataBaseId = 2,
                            Description = "Variable-length string. Max length: 65,535 characters.",
                            HasParams = true,
                            Name = "VARCHAR"
                        },
                        new
                        {
                            Id = 15,
                            DataBaseId = 2,
                            Description = "Variable-length string for large text. Max size: 65,535 bytes.",
                            HasParams = false,
                            Name = "TEXT"
                        },
                        new
                        {
                            Id = 16,
                            DataBaseId = 2,
                            Description = "Variable-length string. Max size: 255 bytes.",
                            HasParams = false,
                            Name = "TINYTEXT"
                        },
                        new
                        {
                            Id = 17,
                            DataBaseId = 2,
                            Description = "Variable-length string. Max size: 16,777,215 bytes.",
                            HasParams = false,
                            Name = "MEDIUMTEXT"
                        },
                        new
                        {
                            Id = 18,
                            DataBaseId = 2,
                            Description = "Variable-length string. Max size: 4,294,967,295 bytes.",
                            HasParams = false,
                            Name = "LONGTEXT"
                        },
                        new
                        {
                            Id = 19,
                            DataBaseId = 2,
                            Description = "Fixed-length binary data. Padded with zeros. Max length: 255 bytes.",
                            HasParams = true,
                            Name = "BINARY"
                        },
                        new
                        {
                            Id = 20,
                            DataBaseId = 2,
                            Description = "Variable-length binary data. Max length: 65,535 bytes.",
                            HasParams = true,
                            Name = "VARBINARY"
                        },
                        new
                        {
                            Id = 21,
                            DataBaseId = 2,
                            Description = "Binary Large Object. Max size: 65,535 bytes.",
                            HasParams = false,
                            Name = "BLOB"
                        },
                        new
                        {
                            Id = 22,
                            DataBaseId = 2,
                            Description = "Binary Large Object. Max size: 255 bytes.",
                            HasParams = false,
                            Name = "TINYBLOB"
                        },
                        new
                        {
                            Id = 23,
                            DataBaseId = 2,
                            Description = "Binary Large Object. Max size: 16,777,215 bytes.",
                            HasParams = false,
                            Name = "MEDIUMBLOB"
                        },
                        new
                        {
                            Id = 24,
                            DataBaseId = 2,
                            Description = "Binary Large Object. Max size: 4,294,967,295 bytes.",
                            HasParams = false,
                            Name = "LONGBLOB"
                        },
                        new
                        {
                            Id = 25,
                            DataBaseId = 2,
                            Description = "Stores date in 'YYYY-MM-DD' format. Range: '1000-01-01' to '9999-12-31'.",
                            HasParams = false,
                            Name = "DATE"
                        },
                        new
                        {
                            Id = 26,
                            DataBaseId = 2,
                            Description = "Stores time in 'HH:MM:SS' format. Range: '-838:59:59' to '838:59:59'.",
                            HasParams = false,
                            Name = "TIME"
                        },
                        new
                        {
                            Id = 27,
                            DataBaseId = 2,
                            Description = "Stores date and time in 'YYYY-MM-DD HH:MM:SS' format. Range: '1000-01-01 00:00:00' to '9999-12-31 23:59:59'.",
                            HasParams = false,
                            Name = "DATETIME"
                        },
                        new
                        {
                            Id = 28,
                            DataBaseId = 2,
                            Description = "Stores UTC timestamp. Range: '1970-01-01 00:00:01' UTC to '2038-01-19 03:14:07' UTC.",
                            HasParams = false,
                            Name = "TIMESTAMP"
                        },
                        new
                        {
                            Id = 29,
                            DataBaseId = 1,
                            Description = "4-byte signed integer. Alias for INTEGER. Range: -2,147,483,648 to 2,147,483,647.",
                            HasParams = false,
                            Name = "INT"
                        },
                        new
                        {
                            Id = 30,
                            DataBaseId = 1,
                            Description = "2-byte signed integer. Range: -32,768 to 32,767.",
                            HasParams = false,
                            Name = "SMALLINT"
                        },
                        new
                        {
                            Id = 31,
                            DataBaseId = 1,
                            Description = "8-byte signed integer. Range: -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807.",
                            HasParams = false,
                            Name = "BIGINT"
                        },
                        new
                        {
                            Id = 32,
                            DataBaseId = 1,
                            Description = "Exact numeric type. Syntax: DECIMAL(precision, scale). Precision: up to 131072 digits.",
                            HasParams = true,
                            Name = "DECIMAL"
                        },
                        new
                        {
                            Id = 33,
                            DataBaseId = 1,
                            Description = "Alias for DECIMAL. Exact numeric type with configurable precision and scale.",
                            HasParams = true,
                            Name = "NUMERIC"
                        },
                        new
                        {
                            Id = 34,
                            DataBaseId = 1,
                            Description = "4-byte floating-point number (single precision). Approximate precision: 6 decimal digits.",
                            HasParams = false,
                            Name = "REAL"
                        },
                        new
                        {
                            Id = 35,
                            DataBaseId = 1,
                            Description = "Fixed-length string. Padded with spaces. Syntax: CHAR(n). Max length: 1GB.",
                            HasParams = true,
                            Name = "CHAR"
                        },
                        new
                        {
                            Id = 36,
                            DataBaseId = 1,
                            Description = "Variable-length string. Syntax: VARCHAR(n). Max length: 1GB.",
                            HasParams = true,
                            Name = "VARCHAR"
                        },
                        new
                        {
                            Id = 37,
                            DataBaseId = 1,
                            Description = "Variable-length string with unlimited length (up to 1GB).",
                            HasParams = false,
                            Name = "TEXT"
                        },
                        new
                        {
                            Id = 38,
                            DataBaseId = 1,
                            Description = "Binary data (equivalent to BLOB in other databases).",
                            HasParams = false,
                            Name = "BYTEA"
                        },
                        new
                        {
                            Id = 39,
                            DataBaseId = 1,
                            Description = "Stores date in 'YYYY-MM-DD' format. Range: 4713 BC to 294276 AD.",
                            HasParams = false,
                            Name = "DATE"
                        },
                        new
                        {
                            Id = 40,
                            DataBaseId = 1,
                            Description = "Stores time in 'HH:MM:SS' format. Includes optional time zone.",
                            HasParams = false,
                            Name = "TIME"
                        },
                        new
                        {
                            Id = 41,
                            DataBaseId = 1,
                            Description = "Stores date and time (without time zone) in 'YYYY-MM-DD HH:MM:SS' format.",
                            HasParams = false,
                            Name = "TIMESTAMP"
                        },
                        new
                        {
                            Id = 42,
                            DataBaseId = 1,
                            Description = "Stores true/false values. Valid inputs: TRUE, FALSE, NULL.",
                            HasParams = false,
                            Name = "BOOLEAN"
                        });
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2025, 3, 1, 19, 5, 5, 52, DateTimeKind.Utc).AddTicks(2980),
                            Email = "admin@gmail.com",
                            Name = "admin",
                            PasswordHash = "$2a$11$ErTwkNFa8slGXV1hZUgZtO0/2r/M7EzSTV/r1lLo70ag9f0syHKku"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2025, 3, 1, 19, 5, 5, 256, DateTimeKind.Utc).AddTicks(5270),
                            Email = "user@gmail.com",
                            Name = "user",
                            PasswordHash = "$2a$11$Eoe0PWyqTuvM0fFWMPzRauC9HrodntQvx.LekZmUAzopcnx/22rI2"
                        });
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Column", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.SqlType", "SqlType")
                        .WithMany("Columns")
                        .HasForeignKey("SqlTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbDesigner.Domain.Domain.Table", "Table")
                        .WithMany("Columns")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SqlType");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.ColumnProperty", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.Column", null)
                        .WithMany()
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbDesigner.Domain.Domain.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Index", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.IndexType", "IndexType")
                        .WithMany()
                        .HasForeignKey("IndexTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndexType");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.IndexColumn", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.Column", null)
                        .WithMany()
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbDesigner.Domain.Domain.Index", null)
                        .WithMany()
                        .HasForeignKey("IndexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.IndexType", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.DataBase", "DataBase")
                        .WithMany("IndexTypes")
                        .HasForeignKey("DataBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataBase");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Orm", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.Language", "Language")
                        .WithMany("Orms")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Project", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.DataBase", "DataBase")
                        .WithMany("Projects")
                        .HasForeignKey("DataBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbDesigner.Domain.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataBase");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Property", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.DataBase", "DataBase")
                        .WithMany()
                        .HasForeignKey("DataBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataBase");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Relation", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.RelationAction", "OnDelete")
                        .WithMany()
                        .HasForeignKey("OnDeleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbDesigner.Domain.Domain.RelationAction", "OnUpdate")
                        .WithMany()
                        .HasForeignKey("OnUpdateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbDesigner.Domain.Domain.Column", "SourceColumn")
                        .WithMany()
                        .HasForeignKey("SourceColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbDesigner.Domain.Domain.Column", "TargetColumn")
                        .WithMany()
                        .HasForeignKey("TargetColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OnDelete");

                    b.Navigation("OnUpdate");

                    b.Navigation("SourceColumn");

                    b.Navigation("TargetColumn");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.SqlType", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.DataBase", "DataBase")
                        .WithMany("SqlTypes")
                        .HasForeignKey("DataBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataBase");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Table", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.Project", "Project")
                        .WithMany("Tables")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.UserRole", b =>
                {
                    b.HasOne("DbDesigner.Domain.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbDesigner.Domain.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.DataBase", b =>
                {
                    b.Navigation("IndexTypes");

                    b.Navigation("Projects");

                    b.Navigation("SqlTypes");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Language", b =>
                {
                    b.Navigation("Orms");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Project", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.SqlType", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("DbDesigner.Domain.Domain.Table", b =>
                {
                    b.Navigation("Columns");
                });
#pragma warning restore 612, 618
        }
    }
}
