<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DbDesigner.Domain\DbDesigner.Domain.csproj" />
      <ProjectReference Include="..\DbDesigner.Infrastructure\DbDesigner.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.AspNetCore.Http.Features">
        <HintPath>..\..\..\..\..\..\..\..\usr\local\share\dotnet\shared\Microsoft.AspNetCore.App\8.0.10\Microsoft.AspNetCore.Http.Features.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.AspNetCore.Mvc.Core" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Docker.DotNet" Version="3.125.15" />
      <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
      <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.0-preview.1.25081.1" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.4" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.0-preview.2.25163.2" />
      <PackageReference Include="MySqlConnector" Version="2.4.0" />
      <PackageReference Include="RabbitMQ.Client" Version="7.1.1" />
      <PackageReference Include="Scriban" Version="6.0.0" />
      <PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.11" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.1.2" />
    </ItemGroup>

</Project>
